export const languages =  
[ {key:'af',value:'af',text:'Afrikaans  '},
{key:'ar',value:'ar',text:'Arabic  '},
{key:'am',value:'am',text:'Amharic  '},
{key:'bn',value:'bn',text:'Bangla  '},
{key:'eu',value:'eu',text:'Basque  '},
{key:'bg',value:'bg',text:'Bulgarian  '},
{key:'ca',value:'ca',text:'Catalan  '},
{key:'zh-HK',value:'zh-HK',text:'Chinese (Hong Kong) '},
{key:'zh-CN',value:'zh-CN',text:'Chinese (Simplified) '},
{key:'zh-TW',value:'zh-TW',text:'Chinese (Traditional) '},
{key:'hr',value:'hr',text:'Croatian  '},
{key:'cs',value:'cs',text:'Czech  '},
{key:'da',value:'da',text:'Danish  '},
{key:'nl',value:'nl',text:'Dutch  '},
{key:'en-GB',value:'en-GB',text:'English (United Kingdom) '},
{key:'en',value:'en',text:'English (United States) '},
{key:'et',value:'et',text:'Estonian  '},
{key:'fil',value:'fil',text:'Filipino  '},
{key:'fi',value:'fi',text:'Finnish  '},
{key:'fr-CA',value:'fr-CA',text:'French (Canada) '},
{key:'fr',value:'fr',text:'French (France) '},
{key:'gl',value:'gl',text:'Galician  '},
{key:'de',value:'de',text:'German  '},
{key:'el',value:'el',text:'Greek  '},
{key:'gu',value:'gu',text:'Gujarati  '},
{key:'iw',value:'iw',text:'Hebrew  '},
{key:'hi',value:'hi',text:'Hindi  '},
{key:'hu',value:'hu',text:'Hungarian  '},
{key:'is',value:'is',text:'Icelandic  '},
{key:'id',value:'id',text:'Indonesian  '},
{key:'it',value:'it',text:'Italian  '},
{key:'ja',value:'ja',text:'Japanese  '},
{key:'kn',value:'kn',text:'Kannada  '},
{key:'ko',value:'ko',text:'Korean  '},
{key:'lv',value:'lv',text:'Latvian  '},
{key:'lt',value:'lt',text:'Lithuanian  '},
{key:'ms',value:'ms',text:'Malay  '},
{key:'ml',value:'ml',text:'Malayalam  '},
{key:'mr',value:'mr',text:'Marathi  '},
{key:'no',value:'no',text:'Norwegian  '},
{key:'fa',value:'fa',text:'Persian  '},
{key:'pl',value:'pl',text:'Polish  '},
{key:'pt-BR',value:'pt-BR',text:'Portuguese (Brazil) '},
{key:'pt-PT',value:'pt-PT',text:'Portuguese (Portugal) '},
{key:'ro',value:'ro',text:'Romanian  '},
{key:'ru',value:'ru',text:'Russian  '},
{key:'sr',value:'sr',text:'Serbian  '},
{key:'sk',value:'sk',text:'Slovak  '},
{key:'sl',value:'sl',text:'Slovenian  '},
{key:'es-419',value:'es-419',text:'Spanish (Latin America) '},
{key:'es',value:'es',text:'Spanish (Spain) '},
{key:'sw',value:'sw',text:'Swahili  '},
{key:'sv',value:'sv',text:'Swedish  '},
{key:'ta',value:'ta',text:'Tamil  '},
{key:'te',value:'te',text:'Telugu  '},
{key:'th',value:'th',text:'Thai  '},
{key:'tr',value:'tr',text:'Turkish  '},
{key:'uk',value:'uk',text:'Ukrainian  '},
{key:'ur',value:'ur',text:'Urdu  '},
{key:'vi',value:'vi',text:'Vietnamese  '},
{key:'zu',value:'zu',text:'Zulu  '} ]