export const languages =
[{key:'af',value:'za',text:'Afrikaans'},
{key:'ar',value:'ar',text:'Arabic'},
{key:'am',value:'am',text:'Amharic'},
{key:'bd',value:'bd',text:'Bangla'},
{key:'bg',value:'bg',text:'Bulgarian'},
{key:'zh-HK',value:'hk',text:'Chinese (Hong Kong)'},
{key:'zh-CN',value:'cn',text:'Chinese (Simplified)'},
{key:'zh-TW',value:'cn',text:'Chinese (Traditional)'},
{key:'hr',value:'hr',text:'Croatian'},
{key:'cs',value:'cs',text:'Czech'},
{key:'da',value:'dk',text:'Danish'},
{key:'nl',value:'nl',text:'Dutch'},
{key:'en',value:'gb',text:'English'},
{key:'et',value:'ee',text:'Estonian'},
{key:'fil',value:'ph',text:'Filipino'},
{key:'fi',value:'fi',text:'Finnish'},
{key:'fr',value:'fr',text:'French'},
{key:'de',value:'de',text:'German'},
{key:'gr',value:'gr',text:'Greek'},
{key:'gu',value:'in',text:'Gujarati'},
{key:'iw',value:'il',text:'Hebrew'},
{key:'hi',value:'in',text:'Hindi'},
{key:'hu',value:'hu',text:'Hungarian'},
{key:'is',value:'is',text:'Icelandic'},
{key:'id',value:'id',text:'Indonesian'},
{key:'it',value:'it',text:'Italian'},
{key:'ja',value:'jp',text:'Japanese'},
{key:'kn',value:'in',text:'Kannada'},
{key:'ko',value:'kr',text:'Korean'},
{key:'lv',value:'lv',text:'Latvian'},
{key:'lt',value:'lt',text:'Lithuanian'},
{key:'ms',value:'my',text:'Malay'},
{key:'ml',value:'in',text:'Malayalam'},
{key:'mr',value:'in',text:'Marathi'},
{key:'no',value:'no',text:'Norwegian'},
{key:'fa',value:'ir',text:'Persian'},
{key:'pl',value:'pl',text:'Polish'},
{key:'pt',value:'pt',text:'Portuguese'},
{key:'ro',value:'ro',text:'Romanian'},
{key:'ru',value:'ru',text:'Russian'},
{key:'sr',value:'cs',text:'Serbian'},
{key:'sk',value:'sk',text:'Slovak'},
{key:'sl',value:'sl',text:'Slovenian'},
{key:'es',value:'es',text:'Spanish'},
{key:'sw',value:'ke',text:'Swahili'},
{key:'sv',value:'se',text:'Swedish'},
{key:'ta',value:'in',text:'Tamil'},
{key:'te',value:'in',text:'Telugu'},
{key:'th',value:'th',text:'Thai'},
{key:'tr',value:'tr',text:'Turkish'},
{key:'uk',value:'ua',text:'Ukrainian'},
{key:'ur',value:'pk',text:'Urdu'},
{key:'vi',value:'vn',text:'Vietnamese'},
{key:'zu',value:'za',text:'Zulu'} ]
