export const languages = [
    {key:'ad',value:'ad',text:'Andorra '},
    {key:'ae',value:'ae',text:'U.A.E '},
    {key:'af',value:'af',text:'Afghanistan '},
    {key:'ag',value:'ag',text:'Antigua '},
    {key:'ai',value:'ai',text:'Anguilla '},
    {key:'al',value:'al',text:'Albania '},
    {key:'am',value:'am',text:'Armenia '},
    {key:'an',value:'an',text:'Netherlands Antilles '},
    {key:'ao',value:'ao',text:'Angola '},
    {key:'ar',value:'ar',text:'Argentina '},
    {key:'as',value:'as',text:'American Samoa '},
    {key:'at',value:'at',text:'Austria '},
    {key:'au',value:'au',text:'Australia '},
    {key:'aw',value:'aw',text:'Aruba '},
    {key:'ax',value:'ax',text:'Aland Islands '},
    {key:'az',value:'az',text:'Azerbaijan '},
    {key:'ba',value:'ba',text:'Bosnia '},
    {key:'bb',value:'bb',text:'Barbados '},
    {key:'bd',value:'bd',text:'Bangladesh '},
    {key:'be',value:'be',text:'Belgium '},
    {key:'bf',value:'bf',text:'Burkina Faso '},
    {key:'bg',value:'bg',text:'Bulgaria '},
    {key:'bh',value:'bh',text:'Bahrain '},
    {key:'bi',value:'bi',text:'Burundi '},
    {key:'bj',value:'bj',text:'Benin '},
    {key:'bm',value:'bm',text:'Bermuda '},
    {key:'bn',value:'bn',text:'Brunei '},
    {key:'bo',value:'bo',text:'Bolivia '},
    {key:'br',value:'br',text:'Brazil '},
    {key:'bs',value:'bs',text:'Bahamas '},
    {key:'bt',value:'bt',text:'Bhutan '},
    {key:'bv',value:'bv',text:'Bouvet Island '},
    {key:'bw',value:'bw',text:'Botswana '},
    {key:'by',value:'by',text:'Belarus '},
    {key:'bz',value:'bz',text:'Belize '},
    {key:'ca',value:'ca',text:'Canada '},
    {key:'cc',value:'cc',text:'Cocos Islands '},
    {key:'cd',value:'cd',text:'Congo '},
    {key:'cf',value:'cf',text:'Central African Republic '},
    {key:'cg',value:'cg',text:'Congo Brazzaville '},
    {key:'ch',value:'ch',text:'Switzerland '},
    {key:'ci',value:'ci',text:'Cote Divoire '},
    {key:'ck',value:'ck',text:'Cook Islands '},
    {key:'cl',value:'cl',text:'Chile '},
    {key:'cm',value:'cm',text:'Cameroon '},
    {key:'cn',value:'cn',text:'China '},
    {key:'co',value:'co',text:'Colombia '},
    {key:'cr',value:'cr',text:'Costa Rica '},
    {key:'cs',value:'cs',text:'Serbia '},
    {key:'cu',value:'cu',text:'Cuba '},
    {key:'cv',value:'cv',text:'Cape Verde '},
    {key:'cx',value:'cx',text:'Christmas Island '},
    {key:'cy',value:'cy',text:'Cyprus '},
    {key:'cz',value:'cz',text:'Czech Republic '},
    {key:'de',value:'de',text:'Germany '},
    {key:'dj',value:'dj',text:'Djibouti '},
    {key:'dk',value:'dk',text:'Denmark '},
    {key:'dm',value:'dm',text:'Dominica '},
    {key:'do',value:'do',text:'Dominican Republic '},
    {key:'dz',value:'dz',text:'Algeria '},
    {key:'ec',value:'ec',text:'Ecuador '},
    {key:'ee',value:'ee',text:'Estonia '},
    {key:'eg',value:'eg',text:'Egypt '},
    {key:'eh',value:'eh',text:'Western Sahara '},
    {key:'er',value:'er',text:'Eritrea '},
    {key:'es',value:'es',text:'Spain '},
    {key:'et',value:'et',text:'Ethiopia '},
    {key:'eu',value:'eu',text:'European Union '},
    {key:'fi',value:'fi',text:'Finland '},
    {key:'fj',value:'fj',text:'Fiji '},
    {key:'fk',value:'fk',text:'Falkland Islands '},
    {key:'fm',value:'fm',text:'Micronesia '},
    {key:'fo',value:'fo',text:'Faroe Islands '},
    {key:'fr',value:'fr',text:'France '},
    {key:'ga',value:'ga',text:'Gabon '},
    {key:'gb',value:'gb',text:'United Kingdom '},
    {key:'gb sct',value:'gb sct',text:'Scotland '},
    {key:'gb wls',value:'gb wls',text:'Wales '},
    {key:'gd',value:'gd',text:'Grenada '},
    {key:'ge',value:'ge',text:'Georgia '},
    {key:'gf',value:'gf',text:'French Guiana '},
    {key:'gh',value:'gh',text:'Ghana '},
    {key:'gi',value:'gi',text:'Gibraltar '},
    {key:'gl',value:'gl',text:'Greenland '},
    {key:'gm',value:'gm',text:'Gambia '},
    {key:'gn',value:'gn',text:'Guinea '},
    {key:'gp',value:'gp',text:'Guadeloupe '},
    {key:'gq',value:'gq',text:'Equatorial Guinea '},
    {key:'gr',value:'gr',text:'Greece '},
    {key:'gs',value:'gs',text:'Sandwich Islands '},
    {key:'gt',value:'gt',text:'Guatemala '},
    {key:'gu',value:'gu',text:'Guam '},
    {key:'gw',value:'gw',text:'Guinea-bissau '},
    {key:'gy',value:'gy',text:'Guyana '},
    {key:'hk',value:'hk',text:'Hong Kong '},
    {key:'hm',value:'hm',text:'Heard Island '},
    {key:'hn',value:'hn',text:'Honduras '},
    {key:'hr',value:'hr',text:'Croatia '},
    {key:'ht',value:'ht',text:'Haiti '},
    {key:'hu',value:'hu',text:'Hungary '},
    {key:'id',value:'id',text:'Indonesia '},
    {key:'ie',value:'ie',text:'Ireland '},
    {key:'il',value:'il',text:'Israel '},
    {key:'in',value:'in',text:'India '},
    {key:'io',value:'io',text:'Indian Ocean Territory '},
    {key:'iq',value:'iq',text:'Iraq '},
    {key:'ir',value:'ir',text:'Iran '},
    {key:'is',value:'is',text:'Iceland '},
    {key:'it',value:'it',text:'Italy '},
    {key:'jm',value:'jm',text:'Jamaica '},
    {key:'jo',value:'jo',text:'Jordan '},
    {key:'jp',value:'jp',text:'Japan '},
    {key:'ke',value:'ke',text:'Kenya '},
    {key:'kg',value:'kg',text:'Kyrgyzstan '},
    {key:'kh',value:'kh',text:'Cambodia '},
    {key:'ki',value:'ki',text:'Kiribati '},
    {key:'km',value:'km',text:'Comoros '},
    {key:'kn',value:'kn',text:'Saint Kitts And Nevis '},
    {key:'kp',value:'kp',text:'North Korea '},
    {key:'kr',value:'kr',text:'South Korea '},
    {key:'kw',value:'kw',text:'Kuwait '},
    {key:'ky',value:'ky',text:'Cayman Islands '},
    {key:'kz',value:'kz',text:'Kazakhstan '},
    {key:'la',value:'la',text:'Laos '},
    {key:'lb',value:'lb',text:'Lebanon '},
    {key:'lc',value:'lc',text:'Saint Lucia '},
    {key:'li',value:'li',text:'Liechtenstein '},
    {key:'lk',value:'lk',text:'Sri Lanka '},
    {key:'lr',value:'lr',text:'Liberia '},
    {key:'ls',value:'ls',text:'Lesotho '},
    {key:'lt',value:'lt',text:'Lithuania '},
    {key:'lu',value:'lu',text:'Luxembourg '},
    {key:'lv',value:'lv',text:'Latvia '},
    {key:'ly',value:'ly',text:'Libya '},
    {key:'ma',value:'ma',text:'Morocco '},
    {key:'mc',value:'mc',text:'Monaco '},
    {key:'md',value:'md',text:'Moldova '},
    {key:'me',value:'me',text:'Montenegro '},
    {key:'mg',value:'mg',text:'Madagascar '},
    {key:'mh',value:'mh',text:'Marshall Islands '},
    {key:'mk',value:'mk',text:'Macedonia '},
    {key:'ml',value:'ml',text:'Mali '},
    {key:'mm',value:'mm',text:'Burma '},
    {key:'mn',value:'mn',text:'Mongolia '},
    {key:'mo',value:'mo',text:'Macau '},
    {key:'mp',value:'mp',text:'Northern Mariana Islands '},
    {key:'mq',value:'mq',text:'Martinique '},
    {key:'mr',value:'mr',text:'Mauritania '},
    {key:'ms',value:'ms',text:'Montserrat '},
    {key:'mt',value:'mt',text:'Malta '},
    {key:'mu',value:'mu',text:'Mauritius '},
    {key:'mv',value:'mv',text:'Maldives '},
    {key:'mw',value:'mw',text:'Malawi '},
    {key:'mx',value:'mx',text:'Mexico '},
    {key:'my',value:'my',text:'Malaysia '},
    {key:'mz',value:'mz',text:'Mozambique '},
    {key:'na',value:'na',text:'Namibia '},
    {key:'nc',value:'nc',text:'New Caledonia '},
    {key:'ne',value:'ne',text:'Niger '},
    {key:'nf',value:'nf',text:'Norfolk Island '},
    {key:'ng',value:'ng',text:'Nigeria '},
    {key:'ni',value:'ni',text:'Nicaragua '},
    {key:'nl',value:'nl',text:'Netherlands '},
    {key:'no',value:'no',text:'Norway '},
    {key:'np',value:'np',text:'Nepal '},
    {key:'nr',value:'nr',text:'Nauru '},
    {key:'nu',value:'nu',text:'Niue '},
    {key:'nz',value:'nz',text:'New Zealand '},
    {key:'om',value:'om',text:'Oman '},
    {key:'pa',value:'pa',text:'Panama '},
    {key:'pe',value:'pe',text:'Peru '},
    {key:'pf',value:'pf',text:'French Polynesia '},
    {key:'pg',value:'pg',text:'New Guinea '},
    {key:'ph',value:'ph',text:'Philippines '},
    {key:'pk',value:'pk',text:'Pakistan '},
    {key:'pl',value:'pl',text:'Poland '},
    {key:'pm',value:'pm',text:'Saint Pierre '},
    {key:'pn',value:'pn',text:'Pitcairn Islands '},
    {key:'pr',value:'pr',text:'Puerto Rico '},
    {key:'ps',value:'ps',text:'Palestine '},
    {key:'pt',value:'pt',text:'Portugal '},
    {key:'pw',value:'pw',text:'Palau '},
    {key:'py',value:'py',text:'Paraguay '},
    {key:'qa',value:'qa',text:'Qatar '},
    {key:'re',value:'re',text:'Reunion '},
    {key:'ro',value:'ro',text:'Romania '},
    {key:'rs',value:'rs',text:'Serbia '},
    {key:'ru',value:'ru',text:'Russia '},
    {key:'rw',value:'rw',text:'Rwanda '},
    {key:'sa',value:'sa',text:'Saudi Arabia '},
    {key:'sb',value:'sb',text:'Solomon Islands '},
    {key:'sc',value:'sc',text:'Seychelles '},
    {key:'sd',value:'sd',text:'Sudan '},
    {key:'se',value:'se',text:'Sweden '},
    {key:'sg',value:'sg',text:'Singapore '},
    {key:'sh',value:'sh',text:'Saint Helena '},
    {key:'si',value:'si',text:'Slovenia '},
    {key:'sj',value:'sj',text:'Jan Mayen '},
    {key:'sk',value:'sk',text:'Slovakia '},
    {key:'sl',value:'sl',text:'Sierra Leone '},
    {key:'sm',value:'sm',text:'San Marino '},
    {key:'sn',value:'sn',text:'Senegal '},
    {key:'so',value:'so',text:'Somalia '},
    {key:'sr',value:'sr',text:'Suriname '},
    {key:'st',value:'st',text:'Sao Tome '},
    {key:'sv',value:'sv',text:'El Salvador '},
    {key:'sy',value:'sy',text:'Syria '},
    {key:'sz',value:'sz',text:'Swaziland '},
    {key:'tc',value:'tc',text:'Caicos Islands '},
    {key:'td',value:'td',text:'Chad '},
    {key:'tf',value:'tf',text:'French Territories '},
    {key:'tg',value:'tg',text:'Togo '},
    {key:'th',value:'th',text:'Thailand '},
    {key:'tj',value:'tj',text:'Tajikistan '},
    {key:'tk',value:'tk',text:'Tokelau '},
    {key:'tl',value:'tl',text:'Timorleste '},
    {key:'tm',value:'tm',text:'Turkmenistan '},
    {key:'tn',value:'tn',text:'Tunisia '},
    {key:'to',value:'to',text:'Tonga '},
    {key:'tr',value:'tr',text:'Turkey '},
    {key:'tt',value:'tt',text:'Trinidad '},
    {key:'tv',value:'tv',text:'Tuvalu '},
    {key:'tw',value:'tw',text:'Taiwan '},
    {key:'tz',value:'tz',text:'Tanzania '},
    {key:'ua',value:'ua',text:'Ukraine '},
    {key:'ug',value:'ug',text:'Uganda '},
    {key:'um',value:'um',text:'Us Minor Islands '},
    {key:'us',value:'us',text:'United States '},
    {key:'uy',value:'uy',text:'Uruguay '},
    {key:'uz',value:'uz',text:'Uzbekistan '},
    {key:'va',value:'va',text:'Vatican City '},
    {key:'vc',value:'vc',text:'Saint Vincent '},
    {key:'ve',value:'ve',text:'Venezuela '},
    {key:'vg',value:'vg',text:'British Virgin Islands '},
    {key:'vi',value:'vi',text:'Us Virgin Islands '},
    {key:'vn',value:'vn',text:'Vietnam '},
    {key:'vu',value:'vu',text:'Vanuatu '},
    {key:'wf',value:'wf',text:'Wallis And Futuna '},
    {key:'ws',value:'ws',text:'Samoa '},
    {key:'ye',value:'ye',text:'Yemen '},
    {key:'yt',value:'yt',text:'Mayotte '},
    {key:'za',value:'za',text:'South Africa '},
    {key:'zm',value:'zm',text:'Zambia '},
    {key:'zw',value:'zw',text:'Zimbabwe '} 
    ]